name: packerin
description: A new Flutter project.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  path_provider: ^2.0.2
  google_fonts: ^3.0.1
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  font_awesome_flutter: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/mountains.jpg
    - assets/logo.png
